#' tar_meta datatable formatting
#'
#' Consistent formatting for simplifying the dispay of tables generated by `envShiny::get_tar_meta`.
#'
#' @format A list, with names to set options for column widths, page length (100, ie enough to (hopefully) show everything), and to remove search/filter functionality.
